clox: test/chunk_test.cpp File Reference
chunk_test.cpp File Reference
#include <gtest/gtest.h>
#include "chunk.h"
Functions
TEST (clox, initChunk)
TEST (clox, freeChunk)
TEST (clox, writeChunk)
Function Documentation
TEST() [1/3]
TEST (clox , freeChunk)
Definition at line 16 of file chunk_test.cpp.
                       {
     Chunk chunk;
     initChunk(&chunk);
     // Add data to chunk...
     int constant = addConstant(&chunk, 1.2);
     writeChunk(&chunk, OP_CONSTANT, 123);
     writeChunk(&chunk, constant, 123);
     // ...then free
     freeChunk(&chunk);
     ASSERT_EQ(chunk.count, 0);
     ASSERT_EQ(chunk.capacity, 0);
     // FIXME ASSERT_EQ(chunk.code, NULL);
     // FIXME ASSERT_EQ(chunk.lines, NULL);
 }
References addConstant(), Chunk::capacity, Chunk::count, freeChunk(), initChunk(), OP_CONSTANT, and writeChunk().
TEST() [2/3]
TEST (clox , initChunk)
Definition at line 5 of file chunk_test.cpp.
                       {
     Chunk chunk;
     initChunk(&chunk);
     ASSERT_EQ(chunk.count, 0);
     ASSERT_EQ(chunk.capacity, 0);
     // FIXME ASSERT_EQ(chunk.code, NULL);
     // FIXME ASSERT_EQ(chunk.lines, NULL);
 }
References Chunk::capacity, Chunk::count, and initChunk().
TEST() [3/3]
TEST (clox , writeChunk)
Definition at line 35 of file chunk_test.cpp.
{
     Chunk chunk;
     initChunk(&chunk);
     // Add data to chunk...
     int constant = addConstant(&chunk, 1.2);
     writeChunk(&chunk, OP_CONSTANT, 123);
     writeChunk(&chunk, constant, 123);
     ASSERT_EQ(chunk.count, 2);
     ASSERT_EQ(chunk.capacity, 8);
     // FIXME ASSERT_EQ(chunk.code, NULL);
     // FIXME ASSERT_EQ(chunk.lines, NULL);
 }
References addConstant(), Chunk::capacity, Chunk::count, initChunk(), OP_CONSTANT, and writeChunk().