clox: src/chunk.h File Reference
chunk.h File Reference
#include "common.h"
#include "value.h"
Data Structures
struct Chunk
Chunk Data Structure.
Enumerations
enum OpCode {
OP_CONSTANT, OP_ADD, OP_SUBTRACT, OP_MULTIPLY,
OP_DIVIDE, OP_NEGATE, OP_RETURN
}
OpCodes.
Functions
void initChunk (Chunk *chunk)
Initialise an empty chunk.
void freeChunk (Chunk *chunk)
Free up the resources used by the given chunk.
void writeChunk (Chunk *chunk, uint8_t byte, int line)
Write a byte to the end of the given chunk.
int addConstant (Chunk *chunk, Value value)
Add a constant value to the given chunk.
Enumeration Type Documentation
OpCode
enum OpCode
OpCodes.
Represent an instruction for the Virtual Machine to execute.
Enumerator
OP_CONSTANT
OP_ADD
OP_SUBTRACT
OP_MULTIPLY
OP_DIVIDE
OP_NEGATE
OP_RETURN
Definition at line 12 of file chunk.h.
              {
     OP_CONSTANT,
     OP_ADD,
     OP_SUBTRACT,
     OP_MULTIPLY,
     OP_DIVIDE,
     OP_NEGATE,
     OP_RETURN,
 } OpCode;
Function Documentation
addConstant()
int addConstant (Chunk * chunk, Value value)
Add a constant value to the given chunk.
Parameters
chunk The chunk add the constant to.
value The constant value.
Returns
int Index of the constant's location in the ValueArray.
Definition at line 34 of file chunk.c.
{
     writeValueArray(&chunk->constants, value);
     return chunk->constants.count - 1;
 }
References Chunk::constants, ValueArray::count, and writeValueArray().
Referenced by main(), and TEST().
freeChunk()
void freeChunk (Chunk * chunk)
Free up the resources used by the given chunk.
Parameters
chunk The chunk to free up.
Definition at line 14 of file chunk.c.
{
     FREE_ARRAY(uint8_t, chunk->code, chunk->capacity);
     FREE_ARRAY(int, chunk->lines, chunk->capacity);
     freeValueArray(&chunk->constants);
     initChunk(chunk);
 }
References Chunk::capacity, Chunk::code, Chunk::constants, FREE_ARRAY, freeValueArray(), initChunk(), and Chunk::lines.
Referenced by main(), and TEST().
initChunk()
void initChunk (Chunk * chunk)
Initialise an empty chunk.
Parameters
chunk The chunk.
Definition at line 6 of file chunk.c.
{
     chunk->count = 0;
     chunk->capacity = 0;
     chunk->code = NULL;
     chunk->lines = NULL;
     initValueArray(&chunk->constants);
 }
References Chunk::capacity, Chunk::code, Chunk::constants, Chunk::count, initValueArray(), and Chunk::lines.
Referenced by freeChunk(), main(), and TEST().
writeChunk()
void writeChunk (Chunk * chunk, uint8_t byte, int line)
Write a byte to the end of the given chunk.
Parameters
chunk The chunk to write to.
byte The byte to add to the end of the chunk.
line The source line the instruction came from.
Definition at line 21 of file chunk.c.
{
     if (chunk->capacity < chunk->count + 1) {
         int oldCapacity = chunk->capacity;
         chunk->capacity = GROW_CAPACITY(oldCapacity);
         chunk->code = GROW_ARRAY(uint8_t, chunk->code, oldCapacity, chunk->capacity);
         chunk->lines = GROW_ARRAY(int, chunk->lines, oldCapacity, chunk->capacity);
     }
     chunk->code[chunk->count] = byte;
     chunk->lines[chunk->count] = line;
     chunk->count++;
 }
References Chunk::capacity, Chunk::code, Chunk::count, GROW_ARRAY, GROW_CAPACITY, and Chunk::lines.
Referenced by main(), and TEST().