clox: src/debug.h File Reference
debug.h File Reference
#include "chunk.h"
Functions
void disassembleChunk (Chunk *chunk, const char *name)
Write a chunk and its data to STDOUT.
int disassembleInstruction (Chunk *chunk, int offset)
Write the OpCode instruction to STDOUT.
Function Documentation
disassembleChunk()
void disassembleChunk (Chunk * chunk, const char * name)
Write a chunk and its data to STDOUT.
Parameters
chunk Chunk to disassemble.
name Name used to identify the chunk.
Definition at line 6 of file debug.c.
{
     printf("== %s ==\n", name);
     for (int offset = 0; offset < chunk->count;) {
         offset = disassembleInstruction(chunk, offset);
     }
 }
References Chunk::count, and disassembleInstruction().
disassembleInstruction()
int disassembleInstruction (Chunk * chunk, int offset)
Write the OpCode instruction to STDOUT.
Parameters
chunk Chunk to read from.
offset Offset from the start of the chunk at which the instruction begins.
Returns
int Offset from the start of the chunk to the next instruction.
Definition at line 26 of file debug.c.
{
     printf("%04d\t", offset);
     if (offset > 0 && chunk->lines[offset] == chunk->lines[offset - 1]) {
         printf("   | ");
     } else {
         printf("%4d ", chunk->lines[offset]);
     }
     uint8_t instruction = chunk->code[offset];
     switch (instruction) {
         case OP_CONSTANT:
             return constantInstruction("OP_CONSTANT", chunk, offset);
         case OP_ADD:
             return simpleInstruction("OP_ADD", offset);
         case OP_SUBTRACT:
             return simpleInstruction("OP_SUBTRACT", offset);
         case OP_MULTIPLY:
             return simpleInstruction("OP_MULTIPLY", offset);
         case OP_DIVIDE:
             return simpleInstruction("OP_DIVIDE", offset);
         case OP_NEGATE:
             return simpleInstruction("OP_NEGATE", offset);
         case OP_RETURN:
             return simpleInstruction("OP_RETURN", offset);
         default:
             printf("Unknown opcode %d\n", instruction);
             return offset + 1;
     }
     printf("\n");
 }
References Chunk::code, constantInstruction(), Chunk::lines, OP_ADD, OP_CONSTANT, OP_DIVIDE, OP_MULTIPLY, OP_NEGATE, OP_RETURN, OP_SUBTRACT, and simpleInstruction().
Referenced by disassembleChunk(), and run().