clox: src/main.c File Reference
main.c File Reference
#include "common.h"
#include "chunk.h"
#include "debug.h"
#include "vm.h"
Functions
int main (int argc, const char *argv[])
Function Documentation
main()
int main (int argc, const char * argv[])
Definition at line 6 of file main.c.
{
     initVM();
     Chunk chunk;
     initChunk(&chunk);
     int constant = addConstant(&chunk, 1.2);
     writeChunk(&chunk, OP_CONSTANT, 123);
     writeChunk(&chunk, constant, 123);
     constant = addConstant(&chunk, 3.4);
     writeChunk(&chunk, OP_CONSTANT, 123);
     writeChunk(&chunk, constant, 123);
     writeChunk(&chunk, OP_ADD, 123);
     constant = addConstant(&chunk, 5.6);
     writeChunk(&chunk, OP_CONSTANT, 123);
     writeChunk(&chunk, constant, 123);
     writeChunk(&chunk, OP_DIVIDE, 123);
     writeChunk(&chunk, OP_NEGATE, 123);
     writeChunk(&chunk, OP_RETURN, 123);
     // disassembleChunk(&chunk, "test chunk");
     interpret(&chunk);
     freeVM();
     freeChunk(&chunk);
     return 0;
 }
References addConstant(), freeChunk(), freeVM(), initChunk(), initVM(), interpret(), OP_ADD, OP_CONSTANT, OP_DIVIDE, OP_NEGATE, OP_RETURN, and writeChunk().