clox: src/value.c File Reference
value.c File Reference
#include <stdio.h>
#include "memory.h"
#include "value.h"
Functions
void initValueArray (ValueArray *array)
Initialise an empty array.
void freeValueArray (ValueArray *array)
Free up the resources used by the given array.
void writeValueArray (ValueArray *array, Value value)
Write a value to the end of the given array.
void printValue (Value value)
Function Documentation
freeValueArray()
void freeValueArray (ValueArray * array)
Free up the resources used by the given array.
Parameters
array The array to free up.
Definition at line 12 of file value.c.
{
     FREE_ARRAY(Value, array->values, array->capacity);
     initValueArray(array);
 }
References ValueArray::capacity, FREE_ARRAY, initValueArray(), and ValueArray::values.
Referenced by freeChunk().
initValueArray()
void initValueArray (ValueArray * array)
Initialise an empty array.
Parameters
array The array.
Definition at line 6 of file value.c.
{
     array->values = NULL;
     array->capacity = 0;
     array->count = 0;
 }
References ValueArray::capacity, ValueArray::count, and ValueArray::values.
Referenced by freeValueArray(), and initChunk().
printValue()
void printValue (Value value)
Definition at line 28 of file value.c.
{
     printf("%g", value);
 }
Referenced by constantInstruction(), and run().
writeValueArray()
void writeValueArray (ValueArray * array, Value value)
Write a value to the end of the given array.
Parameters
array The array to write to.
value The value to add to the end of the array.
Definition at line 17 of file value.c.
{
     if (array->capacity < array->count + 1) {
         int oldCapacity = array->capacity;
         array->capacity = GROW_CAPACITY(oldCapacity);
         array->values = GROW_ARRAY(Value, array->values, oldCapacity, array->capacity);
     }
     array->values[array->count] = value;
     array->count++;
 }
References ValueArray::capacity, ValueArray::count, GROW_ARRAY, GROW_CAPACITY, and ValueArray::values.
Referenced by addConstant().