clox: src/vm.h File Reference
vm.h File Reference
#include "chunk.h"
#include "value.h"
Data Structures
struct VM
Macros
#define STACK_MAX 256
Enumerations
enum InterpretResult { INTERPRET_OK, INTERPRET_COMPILE_ERROR, INTERPRET_RUNTIME_ERROR }
Functions
void initVM ()
void freeVM ()
InterpretResult interpret (Chunk *chunk)
Interpret a chunk of bytecode.
void push (Value value)
Place a value on top of the VM stack.
Value pop ()
Retrieve the value on top of the VM stack.
Macro Definition Documentation
STACK_MAX
#define STACK_MAX 256
Definition at line 7 of file vm.h.
Enumeration Type Documentation
InterpretResult
enum InterpretResult
Enumerator
INTERPRET_OK
INTERPRET_COMPILE_ERROR
INTERPRET_RUNTIME_ERROR
Definition at line 16 of file vm.h.
              {
     INTERPRET_OK,
     INTERPRET_COMPILE_ERROR,
     INTERPRET_RUNTIME_ERROR,
 } InterpretResult;
Function Documentation
freeVM()
void freeVM ()
Definition at line 25 of file vm.c.
               {
 }
Referenced by main().
initVM()
void initVM ()
Definition at line 21 of file vm.c.
               {
     resetStack();
 }
References resetStack().
Referenced by main().
interpret()
InterpretResult interpret (Chunk * chunk)
Interpret a chunk of bytecode.
Further reading to make this method more efficient:
Direct Threaded Code
Jump Table
Computed goto
Parameters
chunk
Returns
InterpretResult
Definition at line 88 of file vm.c.
{
     vm.chunk = chunk;
     vm.ip = vm.chunk->code;
     return run();
 }
References VM::chunk, Chunk::code, VM::ip, run(), and vm.
Referenced by main().
pop()
Value pop ()
Retrieve the value on top of the VM stack.
Returns
Value The value.
Definition at line 34 of file vm.c.
             {
     vm.stackTop--;
     return *vm.stackTop;
 }
References VM::stackTop, and vm.
Referenced by run().
push()
void push (Value value)
Place a value on top of the VM stack.
Parameters
value The value to place on the stack.
Definition at line 29 of file vm.c.
{
     *vm.stackTop = value;
     vm.stackTop++;
 }
References VM::stackTop, and vm.
Referenced by run().