name: JLox CI

on:
  push:
    paths: 
    - 'jlox/**'
    - '.github/workflows/jlox.yml'
  pull_request:
    paths: 
    - 'jlox/**'
    - '.github/workflows/jlox.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: chmod +x jlox/gradlew
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        build-root-directory: jlox
    - name: Test with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: test
        build-root-directory: jlox
    - name: Test Summary
      uses: test-summary/action@v1
      with:
        paths: "jlox/**/*.xml"
      if: always()
